### PR TITLE
Fix #152 and #157 - update the "3d_reconstruction" exercise & the "bump_ang_go" excersise. 

### LINKED ISSUE #152: Update "3d_reconstruction" to use JdeRobotComm

### PR DESCRIPTION
**Pull request by cawadall**
These changes solve issue #152 
- Deleted 3d_reconstruction.cfg and changed to 3d_reconstruction_conf.yml.
- Deleted camera's calibration files and added calibration to yaml file
- Upgraded 3d_reconstruction.py to use JdeRobotComm and .yml configuration files
- Modified some files to work with Comm
- Updated execution instructions in README.md
- GUI simplified.

These changes solve issue #157 
- Deleted unnecessary files to focus the practice through visualStates
- Added support for visualStates
- Updated execution instructions in README.md. Added guide to learn how to use visualStates adapted to this practice.

### CODE REVIEW

**Comment by fqez** [comment]
Hi @cawadall when I try to launch the example following the steps written in README, I got the following error:

```
Traceback (most recent call last):
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/3d_reconstruction/gui/GUI.py", line 34, in updateGUI
    self.camera1.updateImage()
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/3d_reconstruction/gui/widgets/cameraWidget.py", line 28, in updateImage
    if imgLeft != None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Aborted (core dumped)
```

also, in the bump and go practice I get the following error, when launchuing visualStates.py:

```
Traceback (most recent call last):
  File "./visualStates.py", line 24, in <module>
    from gui.visualstates import VisualStates
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/bump_and_go_py/visualStates_py/gui/visualstates.py", line 33, in <module>
    from gui.configdialog import ConfigDialog
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/bump_and_go_py/visualStates_py/gui/configdialog.py", line 24, in <module>
    from gui.jderobotcommconfigdialog import JdeRobotCommConfigDialog
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/bump_and_go_py/visualStates_py/gui/jderobotcommconfigdialog.py", line 21, in <module>
    from gui.interfaces import Interfaces
  File "/media/fran/3f7c5a21-663d-4569-be5e-fa82107b8c92/academy/src/bump_and_go_py/visualStates_py/gui/interfaces.py", line 23, in <module>
    from gui.cmakevars import CMAKE_INSTALL_PREFIX
ImportError: No module named cmakevars
```

**Comment by cawadall** [comment]
Sorry for that @fqez , mine worked as I uploaded it.
I've made the following changes:
- I changed some comparisons to work regardless the data type, hoping to solve the first problem (with numpy arrays)
- I added the missing file to solve the second.
I hope it works with this changes. If not, let me know. Thanks!!

Regards.

**Comment by fqez** [comment]
Hi @cawadall the 3dreconstruction example works fine now, good job!!!
However, the visualStates is still not working. I'm able to generate the python code and launch gazebo, but when I try to run the generated example, it throws the following error:

```
Python$ ./obstacleAvoidancePython.py obstacleAvoidancePython.yml --displaygui=tr
ue
loading Config file ./obstacleAvoidancePython.yml
Publishing obstacleAvoidancePython.myMotors with ICE interfaces
myMotors is connected
Receiving obstacleAvoidancePython.myLaser LaserData from ICE interfaces
myLaser is connected
runtime gui enabled
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/jderobot/lib/python2.7/visualStates_py/codegen/python/state.py", line 93, in run
    if tran.checkCondition():
  File "./obstacleAvoidancePython.py", line 46, in checkCondition
    self.interfaces.calculate_obstacle()
AttributeError: Interfaces instance has no attribute 'calculate_obstacle'
```

I've tried to launch the visualStates_py component to see if my installation is wrong, but using the official VisualStates, this same example works fine, so I assume it is a problem with this example.
The error resides in the generated class ```Interfaces```

### Bump_and_go VisualStates generated class:

```
class Interfaces():
	def __init__(self):
		self.jdrc = None
		self.myMotors = None
		self.myLaser = None

		self.connectProxies()

	def connectProxies(self):
		cfg = config.load(sys.argv[1])
		self.jdrc = comm.init(cfg, "obstacleAvoidancePython")
		self.myMotors = self.jdrc.getMotorsClient("obstacleAvoidancePython.myMotors")
		if not self.myMotors:
			raise Exception("could not create client with name:myMotors")
		print("myMotors is connected")
		self.myLaser = self.jdrc.getLaserClient("obstacleAvoidancePython.myLaser")
		if not self.myLaser:
			raise Exception("could not create client with name:myLaser")
		print("myLaser is connected")

	def destroyProxies(self):
		if self.jdrc is not None:
			self.jdrc.destroy()
```

### Official VisualStates generated class:
```
class Interfaces():
	def __init__(self):
		self.jdrc = None
		self.myMotors = None
		self.myLaser = None
		self.is_obstacle = False

		self.connectProxies()

	def connectProxies(self):
		cfg = config.load(sys.argv[1])
		self.jdrc = comm.init(cfg, "obstacleAvoidancePython")
		self.myMotors = self.jdrc.getMotorsClient("obstacleAvoidancePython.myMotors")
		if not self.myMotors:
			raise Exception("could not create client with name:myMotors")
		print("myMotors is connected")
		self.myLaser = self.jdrc.getLaserClient("obstacleAvoidancePython.myLaser")
		if not self.myLaser:
			raise Exception("could not create client with name:myLaser")
		print("myLaser is connected")

	def destroyProxies(self):
		if self.jdrc is not None:
			self.jdrc.destroy()

	def calculate_obstacle(self):

		threshold_value = 0.4

		laserData = self.myLaser.getLaserData()

		for val in laserData.values:

			if val < threshold_value:

				self.is_obstacle = True

				return

		self.is_obstacle = False
``` 

As you can see, calculate_obstacle function is not present in the b&g visualstates generated class.
 Could you review this please?

Thanks a lot!

**Comment by cawadall** [comment]
Hi @fqez ,

I was told to add only the support for VisualStates (I copied all files from the official one) and a necessary guide (README.md) to correctly use VisualStates. The intention is that the student will make the rest of the job, that is, open VisualStates and write the code for all the functions, states and transitions involved. 
Please, let me know if you have made the function calculate_obstacle() as shown in README.md (VisualStates => click on "Data" tab, and then click on "functions") so I can discard if that is the problem and maybe improve README.md
If not done it, I have uploaded a reference solution to GitLab that you could use to test the practice:
https://gitlab.jderobot.org/JdeRobot-Academy/solutions/tree/master/src/bump_and_go_py
If is doesn't work whit it, also let me know since there would be another problem, but all VisualStates support has been reused from the official, so it should not give problems, I think.

Sorry for that, I wait for your answer to continue.
Thanks and regards!
Carlos.

**Comment by fqez** [comment]
Hi @cawadall and sorry for the lateness. The example you linked me works fine, so I'm merging this!
Very nice job!

**Pull request merged**
